### ISSUE TITLE
Cookbook.md / class cookbook / injection

### ISSUE THREAD

**Issue by jpheos** [BigBigDoudou/ruby#3]
In **cookbook.md**, section **Modélisation du contrôleur**

You propose to your readers:
```ruby
require_relative 'recipe'
require_relative 'cookbook'
require_relative 'view'

def initialize(cookbook)
  @cookbook = cookbook
  @view = View.new
end
```

In fact, you do not need `require_relative 'cookbook'` because you do not use the class `Cookbook` :)

**Comment by BigBigDoudou** [comment]
true that!
